export const ADD_ITEM = "ADD_ITEM";
export const INCREMENT_CART_QUANTITY = "INCREMENT_CART_QUANTITY";
export const DECREMENT_CART_QUANTITY = "DECREMENT_CART_QUANTITY";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const INCREASE_LIKES = "INCREASE_LIKES";
